i win

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,4 +5,55 @@ CACHE_DIR=$2
 
 cd $BUILD_DIR
 
-PATH="$BUILD_DIR/vendor/node/bin:$BUILD_DIR/bin:$BUILD_DIR/node_modules/.bin:$PATH" bower install --config.storage.packages=vendor/bower/packages --config.storage.registry=vendor/bower/registry --config.tmp=vendor/bower/tmp
+needs_resolution() {
+  local semver=$1
+  if ! [[ "$semver" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+install_nodejs() {
+  local version="4.1.1"
+  local dir="$BUILD_DIR/.heroku/node"
+
+  if needs_resolution "$version"; then
+    echo "Resolving node version ${version:-(latest stable)} via semver.io..."
+    local version=$(curl --silent --get --retry 5 --retry-max-time 15 --data-urlencode "range=${version}" https://semver.herokuapp.com/node/resolve)
+  fi
+
+  echo "Downloading and installing node $version..."
+  local download_url="https://s3pository.heroku.com/node/v$version/node-v$version-$os-$cpu.tar.gz"
+  local code=$(curl "$download_url" --silent --fail --retry 5 --retry-max-time 15 -o /tmp/node.tar.gz --write-out "%{http_code}")
+  if [ "$code" != "200" ]; then
+    echo "Unable to download node $version; does it exist?" && false
+  fi
+  tar xzf /tmp/node.tar.gz -C /tmp
+  rm -rf $dir/*
+  mv /tmp/node-v$version-$os-$cpu/* $dir
+  chmod +x $dir/bin/*
+}
+
+install_npm() {
+  local version="3.10.8"
+
+  if [ "$version" == "" ]; then
+    echo "Using default npm version: `npm --version`"
+  else
+    if needs_resolution "$version"; then
+      echo "Resolving npm version ${version} via semver.io..."
+      version=$(curl --silent --get --retry 5 --retry-max-time 15 --data-urlencode "range=${version}" https://semver.herokuapp.com/npm/resolve)
+    fi
+    if [[ `npm --version` == "$version" ]]; then
+      echo "npm `npm --version` already installed with node"
+    else
+      echo "Downloading and installing npm $version (replacing version `npm --version`)..."
+      npm install --unsafe-perm --quiet -g npm@$version 2>&1 >/dev/null
+    fi
+  fi
+}
+
+install_npm
+install_nodejs
+npm install
